export type SeedRoleCode = 'ADMIN' | 'DIRECTOR_OPERATIVO' | 'COORDINADOR' | 'OPERADOR' | 'CAFETERIA';

export const rolePermissionCodes: Record<SeedRoleCode, readonly string[]> = {
  ADMIN: ['*'],
  DIRECTOR_OPERATIVO: [
    'users.read',
    'crews.read',
    'crews.manage',
    'profiles.read',
    'profiles.create',
    'profiles.update',
    'shifts.read',
    'shifts.manage',
    'shifts.approve_overtime',
    'operators.monitor',
    'metrics.audit',
    'reports.read',
    'icebreaker.review',
    'payroll.read',
    'cafeteria.manage',
    'chat.manage',
    'audit.read',
  ],
  COORDINADOR: [
    'users.read',
    'crews.read',
    'crews.manage',
    'profiles.read',
    'profiles.create',
    'profiles.update',
    'shifts.read',
    'shifts.manage',
    'shifts.approve_overtime',
    'operators.monitor',
    'metrics.audit',
    'icebreaker.review',
    'payroll.read',
    'chat.manage',
    'audit.read',
  ],
  OPERADOR: ['profiles.read', 'vault.credential.issue', 'shifts.read', 'payroll.read'],
  CAFETERIA: ['cafeteria.manage', 'chat.manage'],
} as const;
